version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
      - db_data:/app/db
    environment:
      - RACK_ENV=development

volumes:
  gem_cache:
  db_data: